### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by KristianKarl-zz** [rjw57/yt#10]
When searching using Swedish characters, yt crashes.

1) Start yt
2) Press s, and enter search string _Södertälje_, press enter

**Expected result:**
A list if videos

**Actual result:**
A stack trace...

``` bash
[krikar@krikar-thinkpad yt]$ yt
Traceback (most recent call last):
  File "/usr/bin/yt", line 9, in <module>
    load_entry_point('whitey==0.3', 'console_scripts', 'yt')()
  File "/usr/lib/python2.7/site-packages/whitey-0.3-py2.7.egg/yt/__init__.py", line 31, in main
    ui.run()
  File "/usr/lib/python2.7/site-packages/whitey-0.3-py2.7.egg/yt/__init__.py", line 84, in run
    curses.wrapper(self._curses_main)
  File "/usr/lib64/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python2.7/site-packages/whitey-0.3-py2.7.egg/yt/__init__.py", line 128, in _curses_main
    self._run_pager()
  File "/usr/lib/python2.7/site-packages/whitey-0.3-py2.7.egg/yt/__init__.py", line 219, in _run_pager
    self._update_screen()
  File "/usr/lib/python2.7/site-packages/whitey-0.3-py2.7.egg/yt/__init__.py", line 191, in _update_screen
    self._status_bar.addstr(0, 0, truncate(self._status, w-1).encode(self._code))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 28: ordinal not in range(128)
```

Installed yt using Github Master branch, latest commit f1ab093017c5d030aac8e6c0d04e82558f04d915

**Comment by CalumJEadie** [comment]
Thank you for the thorough and structured issue.

I'm not going to be able to look into this for a little while however will keep it open and hope to address it in the future. If you get a chance to look into it we would really appreciate the contribution.

From the stack trace it looks like it is specific to curses rather than the YouTube API.

Calum

**Comment by parkerlreed** [comment]
The reason for this is not using a UTF-8 locale. Changing your system locale to something like en_US.UTF-8 fixes this error.

**Comment by Platway** [comment]
I met a similar problem white trying to search with a keyword in Chinese, using the latest Whitey-0.4

**Comment by dyguan372** [comment]
I update it to python 3, which solves these encoding problems. The forked version is in https://github.com/dyguan372/yt.
