### ISSUE TITLE
Running pi-yt fails

### ISSUE THREAD

**Issue by valkiril** [rjw57/yt#32]
I installed yt on my raspberry pi. When I try to run pi-yt I get:

pi@raspberrypi ~ $ pi-yt
Traceback (most recent call last):
  File "/usr/local/bin/pi-yt", line 9, in <module>
    load_entry_point('whitey==0.4', 'console_scripts', 'pi-yt')()
  File "/usr/local/lib/python2.7/dist-packages/whitey-0.4-py2.7.egg/yt/**init**.py", line 46, in main_with_omxplayer
    ui = Ui(OMXPLAYER_MODE)
  File "/usr/local/lib/python2.7/dist-packages/whitey-0.4-py2.7.egg/yt/**init**.py", line 83, in **init**
    self._player = args.player
AttributeError: 'str' object has no attribute 'player'

Current version of youtube-dl:

pi@raspberrypi ~ $ youtube-dl -U
youtube-dl is up-to-date (2013.12.26)

Python is:

pi@raspberrypi ~ $ python --version
Python 2.7.3

Omxplayer is:

pi@raspberrypi ~ $ omxplayer --version
omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Mon, 16 Dec 2013 22:06:42 +0100
        Version   : b34143c [master]
        Repository: https://github.com/popcornmix/omxplayer.git

**Comment by picketta** [comment]
Same issue on Raspbian Jessie.  Downgrading to 0.3 resolved.

**Comment by hyperreal-info** [comment]
0.3.3~git20131216~b34 on wheezy of raspbian also does not work with the same error

**Comment by mvmn** [comment]
Any progress?

**Comment by rjw57** [comment]
I'm afraid I'm snowed under with work to have time to get the Pi out to debug this. I'm happy to accept pull requests though.

**Comment by mvmn** [comment]
Ok. BTW, I can suggest a workaround that worked for me on Raspberry Pi: don't run pi-yt, run yt instead but specify --player parameter with value "omxplayer" (be sure to install omxplayer first).
I.e. "yt --player omxplayer" makes it work ok on Pi.
