### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by alive-corpse** [rjw57/yt#50]
Tried to install from github (version 0.3) and pip (version 0.4). 

```
~/.local/bin$ ./yt
Traceback (most recent call last):
  File "./yt", line 11, in <module>
    load_entry_point('whitey==0.4', 'console_scripts', 'yt')()
  File "/home/evgeniy/.local/lib/python2.7/site-packages/yt/__init__.py", line 37, in main
    ui.run()
  File "/home/evgeniy/.local/lib/python2.7/site-packages/yt/__init__.py", line 103, in run
    curses.wrapper(self._curses_main)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/evgeniy/.local/lib/python2.7/site-packages/yt/__init__.py", line 147, in _curses_main
    self._run_pager()
  File "/home/evgeniy/.local/lib/python2.7/site-packages/yt/__init__.py", line 221, in _run_pager
    feed = self._get_feed(idx, n_per_page)
  File "/home/evgeniy/.local/lib/python2.7/site-packages/yt/__init__.py", line 188, in _get_feed
    self._last_feed = self._feed['fetch_cb'](start, count, self._ordering)
  File "/home/evgeniy/.local/lib/python2.7/site-packages/yt/__init__.py", line 484, in fetch_cb
    return json.load(urllib2.urlopen('%s?%s' % (url, urllib.urlencode(query))))
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found```

**Comment by timostrating** [comment]
I had the same kind of error in my case it gave a 404 because the following url is down:
http://python-distribute.org/distribute_setup.py

**Comment by jlamoure** [comment]
Also getting this. "Talking to Youtube..." crash.

```
user@host:~ $ yt
Traceback (most recent call last):
  File "/usr/local/bin/yt", line 9, in <module>
    load_entry_point('whitey==0.3', 'console_scripts', 'yt')()
  File "/usr/local/lib/python2.7/dist-packages/whitey-0.3-py2.7.egg/yt/__init__.py", line 38, in main
    ui.run()
  File "/usr/local/lib/python2.7/dist-packages/whitey-0.3-py2.7.egg/yt/__init__.py", line 117, in run
    curses.wrapper(self._curses_main)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/whitey-0.3-py2.7.egg/yt/__init__.py", line 163, in _curses_main
    self._run_pager()
  File "/usr/local/lib/python2.7/dist-packages/whitey-0.3-py2.7.egg/yt/__init__.py", line 237, in _run_pager
    feed = self._get_feed(idx, n_per_page)
  File "/usr/local/lib/python2.7/dist-packages/whitey-0.3-py2.7.egg/yt/__init__.py", line 204, in _get_feed
    self._last_feed = self._feed['fetch_cb'](start, count, self._ordering)
  File "/usr/local/lib/python2.7/dist-packages/whitey-0.3-py2.7.egg/yt/__init__.py", line 607, in fetch_cb
    return json.load(urllib2.urlopen('%s?%s' % (url, urllib.urlencode(query))))
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```
